# Generated by Django 2.0.6 on 2018-06-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180621_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
